Repository healthner/healthner, pull requests merged in 2021-04, with the labels that each got.

#5 [FEAT] Entity 클래스 작성
  src/main/java/com/healthner/healthner/HealthnerApplication.java
  src/main/java/com/healthner/healthner/domain/BaseEntity.java
  src/main/java/com/healthner/healthner/domain/CheckList.java
  src/main/java/com/healthner/healthner/domain/CheckListStatus.java
  src/main/java/com/healthner/healthner/domain/Gym.java
  src/main/java/com/healthner/healthner/domain/Product.java
  src/main/java/com/healthner/healthner/domain/ProductType.java
  src/main/java/com/healthner/healthner/domain/Purchase.java
  src/main/java/com/healthner/healthner/domain/Remain.java
  src/main/java/com/healthner/healthner/domain/Reservation.java
  src/main/java/com/healthner/healthner/domain/Trainer.java
  src/main/java/com/healthner/healthner/domain/User.java
  src/main/resources/application.yml
Labels: 개발

#17 [FEAT] 페이지 대표 색상 수정
  src/main/java/com/healthner/healthner/controller/HealthnerController.java
  src/main/resources/static/css/style.css
  src/main/resources/static/img/healthner-icon.jpg
  src/main/resources/templates/check.html
  src/main/resources/templates/example.html
  src/main/resources/templates/fragments/body-footer.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/gym-mypage.html
  src/main/resources/templates/gymdetail.html
  src/main/resources/templates/home.html
  src/main/resources/templates/new-gym.html
  src/main/resources/templates/new-products.html
  src/main/resources/templates/new-trainer.html
  src/main/resources/templates/purchase.html
  src/main/resources/templates/reservation.html
  src/main/resources/templates/search.html
  src/main/resources/templates/trainer-mypage.html
  src/main/resources/templates/user-mypage.html
Labels: 개발, 스타일

#19 [FEAT] 초기 데이터 세팅
  src/main/java/com/healthner/healthner/domain/CheckList.java
  src/main/java/com/healthner/healthner/domain/Gym.java
  src/main/java/com/healthner/healthner/domain/Product.java
  src/main/java/com/healthner/healthner/domain/Purchase.java
  src/main/java/com/healthner/healthner/domain/Remain.java
  src/main/java/com/healthner/healthner/domain/Reservation.java
  src/main/java/com/healthner/healthner/domain/Trainer.java
  src/main/java/com/healthner/healthner/domain/User.java
  src/main/resources/application.yml
  src/main/resources/data.sql
Labels: 개발, 리뷰

#23 [FEAT] 소셜 로그인 구현
  build.gradle
  libs/gson-2.8.6.jar
  src/main/java/com/healthner/healthner/controller/HealthnerController.java
  src/main/java/com/healthner/healthner/domain/Provider.java
  src/main/java/com/healthner/healthner/domain/User.java
  src/main/java/com/healthner/healthner/kakaologin/KakaoController.java
  src/main/java/com/healthner/healthner/kakaologin/KakaoProfile.java
  src/main/java/com/healthner/healthner/kakaologin/KakaoService.java
  src/main/java/com/healthner/healthner/kakaologin/RetKakaoAuth.java
  src/main/java/com/healthner/healthner/kakaologin/dto/UserDto.java
  src/main/java/com/healthner/healthner/repository/UserRepository.java
  src/main/java/com/healthner/healthner/service/UserService.java
  src/main/resources/application.yml
  src/main/resources/templates/check.html
  src/main/resources/templates/example.html
  src/main/resources/templates/fragments/body-header.html
  src/main/resources/templates/gym-mypage.html
  src/main/resources/templates/gymdetail.html
  src/main/resources/templates/home.html
  src/main/resources/templates/kakaoLogin.html
  src/main/resources/templates/new-gym.html
  src/main/resources/templates/new-products.html
  src/main/resources/templates/new-trainer.html
  src/main/resources/templates/purchase.html
  src/main/resources/templates/reservation.html
  src/main/resources/templates/search.html
  src/main/resources/templates/trainer-mypage.html
  src/main/resources/templates/user-mypage.html
Labels: 개발, 리뷰

#22 [FEAT] DB에 등록된 gym 목록 출력 기능 구현
  src/main/java/com/healthner/healthner/controller/GymApiController.java
  src/main/java/com/healthner/healthner/controller/HealthnerController.java
  src/main/java/com/healthner/healthner/dto/GymDto.java
  src/main/java/com/healthner/healthner/respository/GymRepository.java
  src/main/java/com/healthner/healthner/service/GymService.java
  src/main/resources/data.sql
  src/main/resources/static/css/search.css
  src/main/resources/static/img/marker.png
  src/main/resources/templates/fragments/body-header.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/search.html
  src/test/java/com/healthner/healthner/respository/GymRepositoryTest.java
Labels: 개발, 리뷰

#27 [FEAT] 유저, 어드민 접근 권한 구현
  src/main/java/com/healthner/healthner/config/WebConfig.java
  src/main/java/com/healthner/healthner/controller/HealthnerController.java
  src/main/java/com/healthner/healthner/controller/ReservationController.java
  src/main/java/com/healthner/healthner/domain/User.java
  src/main/java/com/healthner/healthner/interceptor/Auth.java
  src/main/java/com/healthner/healthner/interceptor/AuthInterceptor.java
  src/main/java/com/healthner/healthner/interceptor/Role.java
  src/main/java/com/healthner/healthner/kakaologin/KakaoController.java
  src/main/java/com/healthner/healthner/kakaologin/KakaoService.java
  src/main/java/com/healthner/healthner/kakaologin/dto/UserDto.java
  src/main/java/com/healthner/healthner/repository/UserRepository.java
  src/main/java/com/healthner/healthner/service/UserService.java
  src/main/resources/templates/adminpage.html
  src/main/resources/templates/fragments/body-header.html
  src/main/resources/templates/loginerror.html
Labels: 개발, 기능

#25 [FEAT] 예약 CRUD (user입장)
  src/main/java/com/healthner/healthner/controller/GymApiController.java
  src/main/java/com/healthner/healthner/controller/HealthnerController.java
  src/main/java/com/healthner/healthner/controller/ReservationController.java
  src/main/java/com/healthner/healthner/controller/dto/GymDto.java
  src/main/java/com/healthner/healthner/controller/dto/ReservationDto.java
  src/main/java/com/healthner/healthner/domain/Reservation.java
  src/main/java/com/healthner/healthner/exception/handler/ReservtionNotFoundException.java
  src/main/java/com/healthner/healthner/repository/GymRepository.java
  src/main/java/com/healthner/healthner/repository/ReservationRepository.java
  src/main/java/com/healthner/healthner/service/GymService.java
  src/main/java/com/healthner/healthner/service/ReservationService.java
  src/main/resources/data.sql
  src/main/resources/templates/create-reserv-form.html
  src/main/resources/templates/modify-reserv-form.html
  src/main/resources/templates/reservation.html
  src/main/resources/templates/user-mypage.html
  src/test/java/com/healthner/healthner/respository/GymRepositoryTest.java
Labels: 개발, 기능
