Repository healthner/healthner, pull requests merged in 2021-06, with the labels that each got.

#96 [Deploy] 단일 웹 서버 환경의 container 생성
  Dockerfile
  build.gradle
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/main/resources/templates/fragments/body-header.html
Labels: 개발, 기능, 리뷰, 리팩토링

#99 [Deploy] CD 파이프라인 추가
  Dockerfile
  Dockerfile_DB
  Jenkinsfile
  docker-compose.yml
  src/main/resources/application.yml
Labels: 개발, 기능, 리뷰, 설정

#89 [FEAT] 출석 체크 page 수정
  src/main/java/com/healthner/healthner/controller/GymController.java
  src/main/java/com/healthner/healthner/domain/CheckList.java
  src/main/java/com/healthner/healthner/service/CheckListService.java
  src/main/resources/application.yml
  src/main/resources/static/css/gym.css
  src/main/resources/templates/gym/check.html
Labels: 개발, 리뷰

#103 [DEPLOY] ssh 원격 접속 과정에서 파일 복사 후 명령어 수행 수정
  Jenkinsfile
Labels: 리뷰, 리팩토링, 설정

#104 [FEAT] error page 추가
  src/main/resources/templates/error/4xx.html
  src/main/resources/templates/error/5xx.html
Labels: 개발, 리뷰

#94 [FEAT] 전체적인 프론트 수정
  src/main/resources/static/css/style.css
  src/main/resources/templates/gym/create-gym.html
  src/main/resources/templates/gym/my-page.html
  src/main/resources/templates/loginerror.html
  src/main/resources/templates/reservation/create-form.html
  src/main/resources/templates/trainer/my-page.html
  src/main/resources/templates/user/my-page.html
Labels: 개발, 스타일

#105 [REFACTOR] application yml 설정 파일 분리
  src/main/java/com/healthner/healthner/kakao/KakaoService.java
  src/main/resources/application-dev-oauth.yml
  src/main/resources/application-prod-oauth.yml
  src/main/resources/application.yml
Labels: 개발, 리팩토링

#106 [DEPLOY] 1차 자동 배포 파이프라인 구축
  Jenkinsfile
  build.gradle
  deploy/deploy.sh
  deploy/docker-compose.yml
  src/main/resources/application.yml
  src/test/java/com/healthner/healthner/repository/PurchaseRepositoryTest.java
  src/test/java/com/healthner/healthner/repository/ReservationRepositoryTest.java
Labels: 개발, 기능, 리뷰, 설정, 테스트

#108 [TEST] 1차 릴리즈
  Jenkinsfile
  src/main/resources/application-prod-oauth.yml
Labels: 테스트

#115 [FEAT] 카카오 지도 설정을 위한 수정
  src/main/resources/fullcalendar-5.7.0/LICENSE.txt
  src/main/resources/fullcalendar-5.7.0/README.md
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/gym/detail.html
  src/main/resources/templates/gym/search.html
Labels: 개발

#116 [REFACT] SQL script 인코딩 문제 해결
  src/main/resources/application-prod-oauth.yml
  src/main/resources/application.yml
Labels: 리팩토링

#119 [FEAT] README.md 수정
  README.md
  src/main/resources/application.yml
  src/main/resources/templates/gym/product-form.html
  src/main/resources/templates/home.html
Labels: 리뷰

#120 [Deploy] 컨트롤러의 리턴 경로를 상대 경로로 수정
  src/main/java/com/healthner/healthner/controller/GymController.java
  src/main/java/com/healthner/healthner/controller/PurchaseController.java
  src/main/resources/application.yml
Labels: 리팩토링

#122 [REFACTOR] html 절대 경로 부분 수정
  src/main/resources/templates/error/4xx.html
  src/main/resources/templates/error/5xx.html
  src/main/resources/templates/example.html
Labels: 리팩토링

#123 [REFACTOR] fragments 추가 수정
  src/main/resources/templates/purchase/product-form.html
Labels: 리팩토링

#125 [REFACTOR] calendar 관련 경로 수정
  README.md
  src/main/resources/application.yml
  src/main/resources/templates/reservation/create-form.html
  src/main/resources/templates/trainer/my-page.html
  src/main/resources/templates/trainer/trainer-form.html
  src/main/resources/templates/user/my-page.html
Labels: 리팩토링
