Repository healthner/healthner, pull requests merged in 2021-05, with the labels that each got.

#29 [FEAT] 세션관리, 로그아웃 구현
  src/main/java/com/healthner/healthner/interceptor/AuthUser.java
  src/main/java/com/healthner/healthner/interceptor/AuthUserHandlerMethodArgumentResolver.java
  src/main/java/com/healthner/healthner/kakaologin/KakaoController.java
  src/main/resources/templates/fragments/body-header.html
Labels: 개발, 기능

#32 [REFACTOR] 소스 코드 중간 점검
  src/main/java/com/healthner/healthner/controller/GymController.java
  src/main/java/com/healthner/healthner/controller/HealthnerController.java
  src/main/java/com/healthner/healthner/controller/IndexController.java
  src/main/java/com/healthner/healthner/controller/ReservationController.java
  src/main/java/com/healthner/healthner/controller/TrainerController.java
  src/main/java/com/healthner/healthner/controller/api/GymApiController.java
  src/main/java/com/healthner/healthner/controller/api/ReservationApiController.java
  src/main/java/com/healthner/healthner/controller/dto/ReservationDto.java
  src/main/java/com/healthner/healthner/controller/dto/UserDto.java
  src/main/java/com/healthner/healthner/domain/User.java
  src/main/java/com/healthner/healthner/exception/handler/ReservationNotFoundException.java
  src/main/java/com/healthner/healthner/interceptor/AuthInterceptor.java
  src/main/java/com/healthner/healthner/interceptor/AuthUser.java
  src/main/java/com/healthner/healthner/interceptor/AuthUserHandlerMethodArgumentResolver.java
  src/main/java/com/healthner/healthner/kakao/KakaoController.java
  src/main/java/com/healthner/healthner/kakao/KakaoService.java
  src/main/java/com/healthner/healthner/kakao/RetKakaoAuth.java
  src/main/java/com/healthner/healthner/kakao/dto/KakaoUserInfoDto.java
  src/main/java/com/healthner/healthner/kakaologin/KakaoController.java
  src/main/java/com/healthner/healthner/kakaologin/KakaoProfile.java
  src/main/java/com/healthner/healthner/service/ReservationService.java
  src/main/java/com/healthner/healthner/service/UserService.java
  src/main/resources/application.yml
  src/main/resources/static/css/style.css
  src/main/resources/templates/create-reserv-form.html
  src/main/resources/templates/example.html
  src/main/resources/templates/fragments/body-header.html
  src/main/resources/templates/gym/detail.html
  src/main/resources/templates/gym/mypage.html
  src/main/resources/templates/gym/search.html
  src/main/resources/templates/home.html
  src/main/resources/templates/loginerror.html
  src/main/resources/templates/reservation.html
  src/main/resources/templates/reservation/create-form.html
Labels: 개발, 리뷰, 리팩토링

#35 [FEAT] Gym 등록 수정
  src/main/java/com/healthner/healthner/controller/GymController.java
  src/main/java/com/healthner/healthner/controller/HealthnerController.java
  src/main/java/com/healthner/healthner/controller/dto/GymDto.java
  src/main/java/com/healthner/healthner/domain/Gym.java
  src/main/java/com/healthner/healthner/domain/User.java
  src/main/java/com/healthner/healthner/repository/GymRepository.java
  src/main/java/com/healthner/healthner/service/GymService.java
  src/main/resources/static/css/style.css
  src/main/resources/templates/gym/create-gym.html
  src/main/resources/templates/gym/mypage.html
  src/main/resources/templates/new-gym.html
  src/main/resources/templates/reservation.html
  src/main/resources/templates/user-mypage.html
  src/test/java/com/healthner/healthner/controller/GymControllerTest.java
  src/test/java/com/healthner/healthner/service/GymServiceTest.java
  src/test/resources/data.sql
Labels: 개발, 기능, 리뷰, 리팩토링

#38 [REFACTOR] gson 삭제
  build.gradle
  libs/gson-2.8.6.jar
Labels: 개발

#36 [REFACTOR] PT 예약 관련 코드 리펙토링
  src/main/java/com/healthner/healthner/controller/ReservationController.java
  src/main/java/com/healthner/healthner/controller/dto/ReservationDto.java
  src/main/java/com/healthner/healthner/repository/PurchaseRepository.java
  src/main/java/com/healthner/healthner/repository/ReservationRepository.java
  src/main/java/com/healthner/healthner/service/ReservationService.java
  src/main/resources/data.sql
  src/main/resources/templates/modify-reserv-form.html
  src/main/resources/templates/reservation/create-form.html
  src/main/resources/templates/reservation/modify-form.html
  src/main/resources/templates/user-mypage.html
Labels: 개발, 리뷰, 리팩토링

#39 [FEAT] 트레이너 등록 및 수정 기능 추가
  src/main/java/com/healthner/healthner/config/WebConfig.java
  src/main/java/com/healthner/healthner/controller/HealthnerController.java
  src/main/java/com/healthner/healthner/controller/HomeController.java
  src/main/java/com/healthner/healthner/controller/SearchController.java
  src/main/java/com/healthner/healthner/controller/TrainerController.java
  src/main/java/com/healthner/healthner/controller/model/Message.java
  src/main/java/com/healthner/healthner/domain/Trainer.java
  src/main/java/com/healthner/healthner/dto/TrainerDto.java
  src/main/java/com/healthner/healthner/interceptor/AuthInterceptor.java
  src/main/java/com/healthner/healthner/repository/TrainerRepository.java
  src/main/java/com/healthner/healthner/service/TrainerService.java
  src/main/resources/static/css/new-trainer.css
  src/main/resources/templates/common/message.html
  src/main/resources/templates/fragments/body-header.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/gym/search.html
  src/main/resources/templates/new-trainer.html
  src/main/resources/templates/trainer/trainer-form.html
Labels: 개발, 기능, 리뷰

#44 [REFACTOR] 로그인 부분 전반적인 수정
  src/main/java/com/healthner/healthner/config/WebConfig.java
  src/main/java/com/healthner/healthner/interceptor/AuthInterceptor.java
  src/main/java/com/healthner/healthner/kakao/KakaoController.java
  src/main/java/com/healthner/healthner/kakao/KakaoService.java
  src/main/java/com/healthner/healthner/kakao/dto/KakaoProfile.java
  src/main/java/com/healthner/healthner/kakao/dto/KakaoUserInfoDto.java
  src/main/resources/static/css/style.css
  src/main/resources/static/img/default.png
  src/main/resources/static/img/logo.png
  src/main/resources/templates/fragments/body-header.html
Labels: 개발, 리뷰, 리팩토링

#51 [FEAT] 출석체크 기능 구현
  src/main/java/com/healthner/healthner/controller/GymController.java
  src/main/java/com/healthner/healthner/controller/HealthnerController.java
  src/main/java/com/healthner/healthner/controller/TrainerController.java
  src/main/java/com/healthner/healthner/controller/dto/CheckListDto.java
  src/main/java/com/healthner/healthner/controller/dto/PurchaseDto.java
  src/main/java/com/healthner/healthner/repository/CheckListRepository.java
  src/main/java/com/healthner/healthner/repository/GymRepository.java
  src/main/java/com/healthner/healthner/repository/PurchaseRepository.java
  src/main/java/com/healthner/healthner/service/CheckListService.java
  src/main/java/com/healthner/healthner/service/GymService.java
  src/main/java/com/healthner/healthner/service/PurchaseService.java
  src/main/resources/templates/check.html
  src/main/resources/templates/gym/mypage.html
Labels: 개발, 기능, 리뷰

#48 [FEAT] 트레이너 상품 등록 기능 구현
  src/main/java/com/healthner/healthner/controller/TrainerController.java
  src/main/java/com/healthner/healthner/controller/dto/ProductDto.java
  src/main/java/com/healthner/healthner/controller/dto/TrainerDto.java
  src/main/java/com/healthner/healthner/domain/Product.java
  src/main/java/com/healthner/healthner/domain/Trainer.java
  src/main/java/com/healthner/healthner/repository/ProductRepository.java
  src/main/java/com/healthner/healthner/service/ProductService.java
  src/main/java/com/healthner/healthner/service/TrainerService.java
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/main/resources/static/css/trainer.css
  src/main/resources/templates/fragments/body-header.html
  src/main/resources/templates/trainer/my-page.html
  src/main/resources/templates/trainer/product-form.html
Labels: 개발, 리뷰

#54 [FEAT] 트레이너 my-apge 상품 수정 및 상태 변경 추가
  src/main/java/com/healthner/healthner/controller/TrainerController.java
  src/main/java/com/healthner/healthner/controller/dto/ProductDto.java
  src/main/java/com/healthner/healthner/domain/Product.java
  src/main/java/com/healthner/healthner/repository/ProductRepository.java
  src/main/java/com/healthner/healthner/service/GymService.java
  src/main/java/com/healthner/healthner/service/ProductService.java
  src/main/resources/data.sql
  src/main/resources/templates/trainer/my-page.html
  src/main/resources/templates/trainer/product-form.html
Labels: 개발, 리뷰

#50 [FEAT] Jenkins 설정과 배포시 오류 해결
  Jenkinsfile
  src/main/resources/templates/home.html
  src/test/java/com/healthner/healthner/controller/GymControllerTest.java
  src/test/java/com/healthner/healthner/respository/GymRepositoryTest.java
  src/test/java/com/healthner/healthner/service/GymServiceTest.java
Labels: 개발, 기능, 리뷰, 설정

#55 [FEAT] 기관 상품 관련 기능 개발
  src/main/java/com/healthner/healthner/controller/GymController.java
  src/main/java/com/healthner/healthner/controller/dto/ProductDto.java
  src/main/java/com/healthner/healthner/domain/Product.java
  src/main/java/com/healthner/healthner/repository/ProductRepository.java
  src/main/java/com/healthner/healthner/service/GymService.java
  src/main/java/com/healthner/healthner/service/ProductService.java
  src/main/resources/data.sql
  src/main/resources/templates/gym/my-page.html
  src/main/resources/templates/gym/mypage.html
  src/main/resources/templates/gym/product-form.html
  src/main/resources/templates/reservation/modify-form.html
Labels: 개발, 기능

#57 [FEAT] user my page 구성
  src/main/java/com/healthner/healthner/controller/ReservationController.java
  src/main/java/com/healthner/healthner/controller/UserController.java
  src/main/resources/data.sql
  src/main/resources/static/css/user.css
  src/main/resources/templates/fragments/body-header.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/user-mypage.html
  src/main/resources/templates/user/my-page.html
Labels: 개발, 리뷰

#59 [FEAT] GYM 상세페이지 구현 -기본 세팅
  src/main/java/com/healthner/healthner/controller/GymController.java
  src/main/java/com/healthner/healthner/controller/dto/TrainerDto.java
  src/main/java/com/healthner/healthner/controller/dto/UserDto.java
  src/main/java/com/healthner/healthner/repository/ProductRepository.java
  src/main/java/com/healthner/healthner/repository/TrainerRepository.java
  src/main/java/com/healthner/healthner/service/ProductService.java
  src/main/java/com/healthner/healthner/service/TrainerService.java
  src/main/resources/templates/gym/detail.html
  src/main/resources/templates/gym/search.html
Labels: 개발

#65 [FEAT] main page 작성
  src/main/java/com/healthner/healthner/controller/HomeController.java
  src/main/resources/static/css/home.css
  src/main/resources/static/img/health.jpeg
  src/main/resources/static/img/health.jpg
  src/main/resources/static/img/home/employees.png
  src/main/resources/static/img/home/trainer.png
  src/main/resources/static/img/home/user.png
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/gym/search.html
  src/main/resources/templates/home.html
Labels: 개발, 리뷰

#69 [FEAT] user mypage에 잔여횟수 추가
  src/main/java/com/healthner/healthner/controller/UserController.java
  src/main/java/com/healthner/healthner/controller/dto/RemainDto.java
  src/main/java/com/healthner/healthner/domain/Remain.java
  src/main/java/com/healthner/healthner/repository/RemainRepository.java
  src/main/java/com/healthner/healthner/service/RemainService.java
  src/main/resources/data.sql
  src/main/resources/templates/user/my-page.html
  src/test/resources/data.sql
Labels: 개발, 기능

#71 [FEAT] 코딩 컨벤션 수정 및 gym detail 수정 및 지도 추가
  src/main/java/com/healthner/healthner/controller/GymController.java
  src/main/java/com/healthner/healthner/controller/HealthnerController.java
  src/main/java/com/healthner/healthner/controller/ReservationController.java
  src/main/java/com/healthner/healthner/controller/SearchController.java
  src/main/java/com/healthner/healthner/controller/UserController.java
  src/main/java/com/healthner/healthner/controller/dto/ProductDto.java
  src/main/java/com/healthner/healthner/controller/dto/UserDto.java
  src/main/java/com/healthner/healthner/domain/CheckList.java
  src/main/java/com/healthner/healthner/domain/Gym.java
  src/main/java/com/healthner/healthner/domain/Product.java
  src/main/java/com/healthner/healthner/domain/Purchase.java
  src/main/java/com/healthner/healthner/domain/Remain.java
  src/main/java/com/healthner/healthner/domain/Reservation.java
  src/main/java/com/healthner/healthner/domain/Trainer.java
  src/main/java/com/healthner/healthner/domain/User.java
  src/main/java/com/healthner/healthner/exception/handler/ReservationNotFoundException.java
  src/main/java/com/healthner/healthner/interceptor/AuthInterceptor.java
  src/main/java/com/healthner/healthner/kakao/KakaoController.java
  src/main/java/com/healthner/healthner/repository/CheckListRepository.java
  src/main/java/com/healthner/healthner/repository/GymRepository.java
  src/main/java/com/healthner/healthner/repository/ProductRepository.java
  src/main/java/com/healthner/healthner/repository/PurchaseRepository.java
  src/main/java/com/healthner/healthner/repository/ReservationRepository.java
  src/main/java/com/healthner/healthner/repository/TrainerRepository.java
  src/main/java/com/healthner/healthner/service/CheckListService.java
  src/main/java/com/healthner/healthner/service/GymService.java
  src/main/java/com/healthner/healthner/service/ProductService.java
  src/main/java/com/healthner/healthner/service/PurchaseService.java
  src/main/java/com/healthner/healthner/service/ReservationService.java
  src/main/java/com/healthner/healthner/service/UserService.java
  src/main/resources/data.sql
  src/main/resources/static/css/gym.css
  src/main/resources/static/css/style.css
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/gym/detail.html
  src/main/resources/templates/gym/search.html
Labels: 개발, 리뷰, 리팩토링

#74 [FEAT] 상품 구매 page 기능 구현
  src/main/java/com/healthner/healthner/controller/GymController.java
  src/main/java/com/healthner/healthner/controller/PurchaseController.java
  src/main/java/com/healthner/healthner/controller/UserController.java
  src/main/java/com/healthner/healthner/controller/dto/ProductDto.java
  src/main/java/com/healthner/healthner/domain/Product.java
  src/main/java/com/healthner/healthner/repository/CheckListRepository.java
  src/main/java/com/healthner/healthner/repository/RemainRepository.java
  src/main/java/com/healthner/healthner/service/CheckListService.java
  src/main/java/com/healthner/healthner/service/PurchaseService.java
  src/main/java/com/healthner/healthner/service/RemainService.java
  src/main/resources/data.sql
  src/main/resources/static/css/purchase.css
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/gym/detail.html
  src/main/resources/templates/purchase/product-form.html
  src/main/resources/templates/user/my-page.html
Labels: 개발, 리뷰

#75 [FEAT] gym my page 구현
  src/main/java/com/healthner/healthner/controller/GymController.java
  src/main/resources/static/css/gym.css
  src/main/resources/templates/fragments/body-header.html
  src/main/resources/templates/gym/my-page.html
Labels: 개발, 리뷰

#78 [FEAT] 시설 출석 체크 기능
  src/main/java/com/healthner/healthner/controller/GymController.java
  src/main/java/com/healthner/healthner/controller/UserController.java
  src/main/java/com/healthner/healthner/controller/dto/CheckListDto.java
  src/main/java/com/healthner/healthner/controller/dto/UserDto.java
  src/main/java/com/healthner/healthner/domain/CheckList.java
  src/main/java/com/healthner/healthner/domain/CheckListStatus.java
  src/main/java/com/healthner/healthner/domain/User.java
  src/main/java/com/healthner/healthner/interceptor/AuthInterceptor.java
  src/main/java/com/healthner/healthner/kakao/KakaoController.java
  src/main/java/com/healthner/healthner/repository/CheckListRepository.java
  src/main/java/com/healthner/healthner/service/CheckListService.java
  src/main/java/com/healthner/healthner/service/UserService.java
  src/main/resources/data.sql
  src/main/resources/templates/check.html
  src/main/resources/templates/number-form.html
Labels: 개발, 기능, 리뷰, 리팩토링

#80 [FEAT]PT상품 예약 시 count 감소
  src/main/java/com/healthner/healthner/controller/PurchaseController.java
  src/main/java/com/healthner/healthner/controller/ReservationController.java
  src/main/java/com/healthner/healthner/controller/dto/RemainDto.java
  src/main/java/com/healthner/healthner/controller/dto/ReservationDto.java
  src/main/java/com/healthner/healthner/domain/Remain.java
  src/main/java/com/healthner/healthner/domain/Reservation.java
  src/main/java/com/healthner/healthner/repository/RemainRepository.java
  src/main/java/com/healthner/healthner/repository/ReservationRepository.java
  src/main/java/com/healthner/healthner/service/PurchaseService.java
  src/main/java/com/healthner/healthner/service/RemainService.java
  src/main/java/com/healthner/healthner/service/ReservationService.java
  src/main/resources/data.sql
  src/main/resources/templates/purchase/purchase.html
  src/main/resources/templates/reservation/create-form.html
  src/main/resources/templates/reservation/modify-form.html
  src/main/resources/templates/user/my-page.html
Labels: 개발, 기능, 리뷰

#84 [FEAT] main page 수정
  src/main/java/com/healthner/healthner/controller/HealthnerController.java
  src/main/resources/static/css/home.css
  src/main/resources/static/css/style.css
  src/main/resources/static/img/about/kakao.jpg
  src/main/resources/static/img/about/map.png
  src/main/resources/static/img/about/online.jpg
  src/main/resources/static/img/about/person.jpg
  src/main/resources/static/img/heallogo.png
  src/main/resources/static/img/health1.jpg
  src/main/resources/static/img/healthlogo.png
  src/main/resources/static/img/healthner.png
  src/main/resources/templates/about.html
  src/main/resources/templates/fragments/body-header.html
  src/main/resources/templates/home.html
Labels: 개발, 스타일

#82 [FEAT] 지도 infoWindow에 이용자 수가 표시 및 main page 수정
  src/main/java/com/healthner/healthner/controller/HomeController.java
  src/main/java/com/healthner/healthner/controller/api/CheckListApiController.java
  src/main/java/com/healthner/healthner/controller/dto/CheckListDto.java
  src/main/java/com/healthner/healthner/controller/dto/GymDto.java
  src/main/java/com/healthner/healthner/repository/CheckListRepository.java
  src/main/java/com/healthner/healthner/service/CheckListService.java
  src/main/resources/data.sql
  src/main/resources/static/css/home.css
  src/main/resources/static/css/search.css
  src/main/resources/static/css/style.css
  src/main/resources/templates/fragments/body-footer.html
  src/main/resources/templates/gym/search.html
  src/main/resources/templates/home.html
Labels: 개발, 기능

#91 [FEAT}마이페이지 프론트 정리
  src/main/java/com/healthner/healthner/controller/UserController.java
  src/main/java/com/healthner/healthner/controller/dto/PurchaseDto.java
  src/main/java/com/healthner/healthner/controller/dto/RemainDto.java
  src/main/java/com/healthner/healthner/controller/dto/ReservationDto.java
  src/main/java/com/healthner/healthner/domain/Purchase.java
  src/main/java/com/healthner/healthner/domain/Remain.java
  src/main/java/com/healthner/healthner/domain/Reservation.java
  src/main/resources/data.sql
  src/main/resources/static/css/user.css
  src/main/resources/static/img/black.jpg
  src/main/resources/static/js/bootstrap/css/bootstrap.min.css
  src/main/resources/templates/purchase/purchase.html
  src/main/resources/templates/reservation/create-form.html
  src/main/resources/templates/user/my-page.html
Labels: 개발, 스타일

#92 [FEAT] gym,trainer my page 프론트 수정
  src/main/resources/static/css/gym.css
  src/main/resources/static/css/trainer.css
  src/main/resources/templates/gym/my-page.html
  src/main/resources/templates/trainer/my-page.html
Labels: 개발, 스타일
